# Set all versions
CUSTOM_BUILD_TYPE ?= test-keys
CUSTOM_BUILD_DATE := $(shell date +%Y%m%d.%H%M%S)
CUSTOM_PLATFORM_VERSION := 9

TARGET_PRODUCT_SHORT := $(subst aosp_,,$(CUSTOM_BUILD))

ifeq ($(IS_GO_VERSION), true)
CUSTOM_VERSION := aosp_go_$(CUSTOM_BUILD)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_BUILD_TYPE)
ROM_FINGERPRINT := aosp_go/$(CUSTOM_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(CUSTOM_BUILD_DATE)
else
# CUSTOM_VERSION := aosp_$(CUSTOM_BUILD)-$(TARGET_BUILD_VARIANT)-$(CUSTOM_PLATFORM_VERSION)-$(CUSTOM_BUILD_DATE)-$(CUSTOM_BUILD_TYPE)
CUSTOM_VERSION := aosp_$(CUSTOM_BUILD)-$(TARGET_BUILD_VARIANT)-$(CUSTOM_PLATFORM_VERSION)-$(BUILD_ID)-$(CUSTOM_BUILD_DATE)
ROM_FINGERPRINT := aosp/$(CUSTOM_PLATFORM_VERSION)/$(TARGET_PRODUCT_SHORT)/$(CUSTOM_BUILD_DATE)
endif
